### PR TITLE
Disable most of the builds on travis CI

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 

This disables many of the builds on Travis CI (commenting) in order to reduce the footprint of our builds.

* **Does this PR introduce a breaking change?** 

No.

* **Other information**:

### CODE REVIEW

**Review by aulemahal — APPROVED** [review]

**Comment by aulemahal** [comment]
I note that no builds were performed this week, other than this one. So the deactivation did work. The dashboard says we are at 8k minutes this month (since Nov 2nd).

**Review by tlvu — APPROVED** [review]
LGTM

**Comment by tlvu** [comment]
> The dashboard says we are at 8k minutes this month (since Nov 2nd).

I went here https://travis-ci.com/dashboard, with my login, and did not see our remaining limits.  How did you see that?

**Comment by aulemahal** [comment]
https://travis-ci.com/github/Ouranosinc?tab=insights

It's not the remaining minutes, it seems to be only the total _used_ minutes, this month.

**Comment by Zeitsperre** [comment]
> It's not the remaining minutes, it seems to be only the total _used_ minutes, this month.

That information is not very useful for us. Not great.

**Pull request merged**
