### PR TITLE
FIX: Standardize method applied on individual variables in OTC/dOTC

### PR DESCRIPTION
**Pull request by coxipi**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [ ] CHANGELOG.rst has been updated (with summary of main changes)
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* The mean and std in the 'standardize' normalization method of OTC/dOTC now is correctly applied on each variable individually
* While we're at it, I suggest changing the argument `transform` to `normalization` which I feel is more specific and informative. Also, in `optimal_transport`, we should follow the snake convention, `numIterMax` -> `num_iter_max` (I guess this was done to imitate the signature of `ot.emd`, but I think we need to stick to a standard in `xclim` functions)

### Does this PR introduce a breaking change?
* `transform` -> `normalization` in input arguments.

### CODE REVIEW

**Review by Zeitsperre — APPROVED** [review]
This seems like a fine change. The `transform` signature is very new, so no need for a deprecation warning message. Just need to update the CHANGELOG.

**Comment by coxipi** [comment]
@SarahG-579462  Thoughts on these changes? Especially `transform` -> `normalization` which is a matter of taste.

**Comment by coxipi** [comment]
It's a step in the right direction, but that's not even what I had in mind for the standardization. Right now, we just remove the mean/std of the cells, but those are simply evenly distributed. So, it doesn't say much about the distributions at hand, we don't have the information of the probability of each cell (or the count). Perhaps a proper standardization would not work well, but this remains to be seen

**Review by SarahG-579462 — APPROVED** [review]
This looks good. Did you want to include your work with the time step vs grid cell motion, or do you want that in a different PR?

**Comment by coxipi** [comment]
Maybe the dOTC evolution through cells (more fidel to the paper) can wait another PR. But: 

```python
    def _standardize(grid, mu):
        mu0 = mu.reshape(len(mu), 1)
        mean = (mu0*grid).sum(axis=0)
        std =  np.sqrt((mu0*(grid**2-mean**2)).sum(axis=0))
        return (grid-mean)/std
   
    # this actually computes  `( X - mean(X) ) / std(X)`
    if normalization == "standardize":
        gridX = _standardize(gridX, muX)
        gridY = _standardize(gridY, muY)

    # this is the old way, it computes `(gridX - mean(gridX) ) / std(gridX)`
    elif normalization  == "standardize_cells":
        gridX = (gridX - gridX.mean(axis=0)) / gridX.std(axis=0)
        gridY = (gridY - gridY.mean(axis=0)) / gridY.std(axis=0)
        
```

The differences are not huge though:

image

**Comment by coxipi** [comment]
I'll just merge this PR now, other changes can be in another PR.

**Pull request merged**
