### PR TITLE
Use convert_calendar in ensemble alignment

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 
Instead of implicitly doing the calendar conversion, `ensembles.create_ensemble` now has an explicit option to control the output calendar. Control is minimal: only the calendar name can be modified and the default options of  `convert_calendar` are used.

In fact, I broke `create_ensemble` in the last PR that modified the alignment process, but didn't realize until now. '360_day' calendar were broken because of the 30th of Feb. This fix has the same default behaviour than the old code and adds some control.

* **Does this PR introduce a breaking change?** 
No, the default for the `calendar` argument is `default`. 

* **Other information**:

### CODE REVIEW

**Comment by tlogan2000** [comment]
@aulemahal If you are working on ensembles.py I recently had the idea of implementing a `add_perc_as_dim`  flag.   Default would be `False` and would run as currently implemented creating a new variable for each percentile.  If ``True`` the output would be a single dataarray with added 'percentile' dim ( coords == input percntiles).  It should be somewhat 'cleaner' if users want a larger number of percentiles.   I think we could calculate all percentiles at once even instead of looping over values as we do currently?

We could make this a separate issue I suppose

@huard opinion on a 'add_perc_as_dim' option?

**Comment by aulemahal** [comment]
I think it's a good idea! I would also suggest to have this in a separate PR/issue. Shouldn't be difficult to implement. Also, while doing this, we should make ensemble_percentiles work on DataArrays too, the current code is unneedingly dataset-only.

**Comment by tlogan2000** [comment]
> I think it's a good idea! I would also suggest to have this in a separate PR/issue. Shouldn't be difficult to implement. Also, while doing this, we should make ensemble_percentiles work on DataArrays too, the current code is unneedingly dataset-only.

Sounds good to me .. can you open an new issue?  I will try to take a look at this PR in the meantime.  Seems fairly straightforward

**Comment by huard** [comment]
I would suggest reviewing the API for this. It seems to me the *natural* xarray approach would be to always have this new percentile dimension. Then, when writing to file, you could have a `split` method to create individual files for each percentile value.

**Pull request merged**
