### PR TITLE
Fix the Bottleneck@master Travis CI build

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 

Add the apt package `python-dev` to the Travis-CI build that uses Bottleneck@master

* **Does this PR introduce a breaking change?** 

Not to my knowledge. The opposite, in fact.

* **Other information**:

~`python-dev` does not come pre-installed on a `python`-based Travis CI build, apparently.~ My mistake, looks like it does.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
This doesn't seem to have fixed it. `python-dev` is installed by default. Must be something else preventing Bottleneck from being built in Travis CI.

**Comment by Zeitsperre** [comment]
I've got bad news for you; There's probably more coming on this one. Might be a "Squash+Merge" scenario, if you catch my drift.

**Comment by tlvu** [comment]
> I've got bad news for you; There's probably more coming on this one. Might be a "Squash+Merge" scenario, if you catch my drift.

Well ... why even bother squash+merge?  The one single commit not even working, abandon it and start a new branch !!!

**Comment by Zeitsperre** [comment]
Point taken. Will try a different approach!

**Pull request closed without merging**
