### PR TITLE
Bugfix: distribution fit broken with empty arrays (when full of nans).

### LINKED ISSUE #292: frequency_analysis crashes if there are empty grid cells
* xclim version: 0.11.2
* Python version: 3.6
* Operating System:

### Description
I have a Dataset on a rotated grid (EC-EARTH_HIRHAM5, from CORDEX-NA). I've made a subset for my region, and on the borders of that subset, some grid cells are empty (meaning that all values are NaN).

Following a call to frequency_analysis, the code crashes if I try to save the data to NetCDF, or even with a simple ".values" call. I receive the following error:
ValueError: zero-size array to reduction operation minimum which has no identity

### What I Did
```
import xarray as xr
from xclim import subset
from xclim import generic as xcgen

ds = xr.open_mfdataset("/path/to/rotated/pole/data")  <--- EC-EARTH_HIRHAM5 hourly precipitation for the 1981-2010 period
ds_subset = subset.subset_bbox(ds, lat_bnds=lat_bnds, lon_bnds=lon_bnds)
da_freq = xcgen.frequency_analysis(ds_subset["pr"], mode="max", t=2, dist="genextreme", window=6, freq="YS")
da_freq.isel(return_period=0).values  <-- crashes
```

If I use the following code, everything works fine (except that I get data in locations that should be NaN):
```
import xarray as xr
from xclim import subset
from xclim import generic as xcgen

ds = xr.open_mfdataset("/path/to/rotated/pole/data")
ds_subset = subset.subset_bbox(ds, lat_bnds=lat_bnds, lon_bnds=lon_bnds)
ds_subset["pr"] = ds_subset["pr"].fillna(value=0)  <-- this is the new line
da_freq = xcgen.frequency_analysis(ds_subset["pr"], mode="max", t=2, dist="genextreme", window=6, freq="YS")
da_freq.isel(return_period=0).values  
```

### PR DESCRIPTION
**Pull request by huard**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated

### After merging to master and before closing the branch:
- [ ] bumpversion (minor / major / patch) has been called on `master` branch
- [ ] Tags have been pushed

* **What kind of change does this PR introduce?** 
Bug fix. 

* **Does this PR introduce a breaking change?** 
No. 

* **Other information**:

This PR fixes #292

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@huard There are a few CodeFactor fixes that would be good to implement before merging, mainly adding assertion checks to new tests.

**Comment by huard** [comment]
@Zeitsperre On it. However, I don't like some of the things Black is doing to the code. The line
```
return len(dist_params) * [np.nan, ]
```
is needlessly split over 3 lines. Is there anything we can do about this ?

@RondeauG Realized I did not really deal with single NaNs (only all NaNs over either time or space).  Fix coming.

**Comment by RondeauG** [comment]
True. I think that the previous `dropna` was there to deal with missing years of data, which I don't have.

**Comment by huard** [comment]
@Zeitsperre I'd like to merge this one but the 3.5 install seems to have failed. Ideas ?

**Comment by Zeitsperre** [comment]
@huard Looks good. Some failures I've noted are sometime because of an unavailable source library or wheel, or even just a disconnection. Not sure why it happens, but restarting the build will often fix it.

**Comment by huard** [comment]
Merged. Bumpversion adds a beta to the version... expected ?

**Comment by tlogan2000** [comment]
@Zeitsperre can help here...  there's an extra step I beleive.  bumpversion 'release' or similar?

**Pull request merged**
