### PR TITLE
Use Issue Forms

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR exapands upon #886 
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [ ] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.
- [ ] `bumpversion patch` has been called on this branch
- [ ] The relevant author information has been added to `.zenodo.json`

### What kind of change does this PR introduce?

* This PR adds issue forms, which are a structured way of asking for required information from users/devs on bug reports, support tickets, and enhancements requests.
* Adjusted YAML formatting

### Does this PR introduce a breaking change?

No.

### Other information:

Feel free to suggest changes or simplifications to the approach. I added in what I think makes the most sense, but this is to better aid us as a group.

### CODE REVIEW

**Review by tlogan2000 — APPROVED** [review]

**Comment by huard** [comment]
Is there a way we could test it in action before merging ? I'm not convinced this is going to be useful at this point in xclim's development.

**Comment by juliettelavoie** [comment]
When we submit a new issue, will it be mandatory to use one of those templates or will there also be a "empty template" choice  ?

**Comment by Zeitsperre** [comment]
@huard There's no way to test beforehand. We could merge, try it out, and roll back the commit, though. 

@juliettelavoie There's still the option of opening a generic issue, which will load the typical schema we have currently (https://github.com/Ouranosinc/xclim/blob/master/.github/ISSUE_TEMPLATE.md). Blank issues are permitted, but we could specify right at the top of the list that the default ticket is the ISSUE_TEMPLATE.md.

**Comment by Zeitsperre** [comment]
@huard I think this is ready. I've made a generic issue form as the topmost form, with one content box, so effectively the same as what we have currently, but we have the option of opening blank forms as well. I would suggest merging this, seeing whether we like it or not, and making changes/reverting it in another PR. What do you think?

**Pull request merged**
