### PR TITLE
Fix TypeError when adjusting with preloaded training dataset

### LINKED ISSUE #1678: QuantileDeltaMapping adjustment in Dask fails if training dataset has been loaded
### Setup Information

- Xclim version: 0.47.0
- Python version: 311.6
- Operating System: Ubuntu 18.04

### Description

When I modify the example from the [docs](https://xclim.readthedocs.io/en/stable/notebooks/sdba-advanced.html#Frequency-adaption-with-a-rolling-window) to run the QuantileDeltaMapping in Dask, it fails during adjustment if I load the dataset after training. 

As you can see in the example below, all I did is add chunking to `ref` and `sim`. I then load the `qdm.ds` to make sure that training is performed. In my real world example, I want to do this because I will adjust multiple simulations with the same training dataset. In fact, the same xclim example recommends doing this.

The error message (`TypeError: object of type 'NoneType' has no len()`) points to *xclim/sdba/base.py:606*. 
These are the lines
```python 
                badchunks.update(
                    {
                        dim: chunks.get(dim)
                        for dim in reduced_dims
                        if len(chunks.get(dim)) > 1
                    }
```

`reduced_dims` are `groups` and `quantiles` which aren't in `chunks` after I called `load` on `qdm.ds`. That's why `chunks.get(dim)` return NoneType which explains the error message.

In fact, just  2 lines above xclim seems to anticipate this case by returning an empty list by default (L599 `if len(chunks.get(dim, [])) > 1`).

I suggest to use the same approach to fix this issue. Happy to make a PR.

### Steps To Reproduce

```python
import xarray as xr
import numpy as np
from xclim.sdba import QuantileDeltaMapping

t = xr.cftime_range("2000-01-01", "2030-12-31", freq="D", calendar="noleap")
ref = xr.DataArray(
    (
        -20 * np.cos(2 * np.pi * t.dayofyear / 365)
        + 2 * np.random.random_sample((t.size,))
        + 273.15
        + 0.1 * (t - t[0]).days / 365
    ),  # "warming" of 1K per decade,
    dims=("time",),
    coords={"time": t},
    attrs={"units": "K"},
).chunk({"time": -1})
sim = xr.DataArray(
    (
        -18 * np.cos(2 * np.pi * t.dayofyear / 365)
        + 2 * np.random.random_sample((t.size,))
        + 273.15
        + 0.11 * (t - t[0]).days / 365
    ),  # "warming" of 1.1K per decade
    dims=("time",),
    coords={"time": t},
    attrs={"units": "K"},
).chunk({"time": -1})

ref = ref.sel(time=slice(None, "2015-01-01"))
hist = sim.sel(time=slice(None, "2015-01-01"))

qdm = QuantileDeltaMapping.train(ref, hist, group="time", kind="+")
qdm.ds.load()
adjusted = qdm.adjust(sim)
```

### Additional context

_No response_

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by saschahofmann**
See issue #1678 for an explanation of the problem

Now, returns an empty list if a reduced dimension is not in the dataset chunks in xclim/sdba/base.py map_blocks when checking for badchunks.

### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #1678 
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGES.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

Returns an empty list if a reduced dimension is not in the dataset chunks in xclim/sdba/base.py map_blocks when checking for badchunks

### Does this PR introduce a breaking change?
No.

### CODE REVIEW

**Review by aulemahal — APPROVED** [review]
Looks good!
Sorry for overlooking that case and thanks for the fix!

**Comment by saschahofmann** [comment]
No problem at all.

Do I need to look into that failing check or is that expected?

**Review by Zeitsperre — APPROVED** [review]

**Comment by saschahofmann** [comment]
Alright if you insist. Also added a comment to the unreleased 0.49.0 bug fixes

**Comment by Zeitsperre** [comment]
@saschahofmann You can also add your info to the Zenodo file as well so that you get properly cited when the package is published there. I leave that decision up to you!

**Comment by saschahofmann** [comment]
I'll do that once I make a note worthy contribution 👍😉

**Pull request merged**
