### PR TITLE
Fix 512

### LINKED ISSUE #512: generic.fit incorrectly orders dimensions
* xclim version: 0.18.1-beta

### Description

Works as long as time is the first dimension, breaks otherwise (I think). 
For example, 
`xclim.indices.generic.fit(da)`  where `da` has dimensions `(site, time)`.

### PR DESCRIPTION
**Pull request by huard**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #512
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 
Bug fix.

* **Does this PR introduce a breaking change?** 
No.

* **Other information**:

### CODE REVIEW

**Comment by huard** [comment]
Should we fix the Kmeans issues before merging this ?

**Comment by aulemahal** [comment]
The issue is quite small, so yes, I would suggest simply changing our "expected" value and pin scikit-learn at 0.23.2.

**Comment by huard** [comment]
It feels heavy-handed to pin a dependency for no other reason that make sure tests pass (no new critical feature).

**Comment by aulemahal** [comment]
Then we could simple update the "importorskip" pytest statement to 0.23.2 (and change the expected output)?

**Pull request merged**
