### PR TITLE
Fix 270

### PR DESCRIPTION
**Pull request by huard**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated

### After merging to master and before closing the branch:
- [ ] bumpversion (minor / major / patch) has been called on `master` branch
- [ ] Tags have been pushed

* **What kind of change does this PR introduce?** 

* **Does this PR introduce a breaking change?** 

* **Other information**:

This PR fixes #xyz

### CODE REVIEW

**Comment by Zeitsperre** [comment]
This should finally deal with the conflicts. Pre-commit wasn't using the setup.cfg overrides. Now it does.

**Comment by tlogan2000** [comment]
`_check_desc_coords` can probably be integrated into assign bounds now that I look closer

**Comment by Zeitsperre** [comment]
Everything seems to be passing from what I can see. Nothing should be failing.

**Comment by tlogan2000** [comment]
one FutureWarning remaining in tests/test_streamflow.py::test_qdoy_max
```
/home/travis/build/Ouranosinc/xclim/.tox/py36/lib/python3.6/site-packages/xarray/core/groupby.py:594: FutureWarning: This DataArray contains multi-dimensional coordinates. In the future, these coordinates will be transposed as well unless you specify transpose_coords=False.
    return stacked.transpose(*new_order, transpose_coords=self._restore_coord_dims)

**Comment by huard** [comment]
I *think* this is coming from xarray itself.

**Comment by tlogan2000** [comment]
Tests passed on the last build (before I pushed the updated history.rst).  subset_bbox could use some attention and  be simplified a bit but I will approve this as is as everything is back to working order. We can maybe try to clean up subset.py in another issue.

**Comment by Zeitsperre** [comment]
I wouldn't worry too much about the CodeFactor checks. Those are mainly there to track TODO's and warn us of potentially unmaintainable code (ie: complex code). If it passes Travis CI, it's good.

**Comment by tlogan2000** [comment]
Added test addressing https://github.com/Ouranosinc/xclim/issues/270#issuecomment-532847772

**Pull request merged**
