### PR TITLE
Restructure xclim

### LINKED ISSUE #374: Restructure the utility functions and move decorators to dedicated folder
A follow up on the code review discussion this morning identified the need to move our utility functions closer to the indices and other calculations that rely on them. In addition, in order to reduce the complexity of many files, another proposal is to move the decorators that are numerous within many files to their own folder within this structure.

This would effectively change xclim by modifying its folder structure to resemble something similar to the following:

```
xclim
    -> Indicators/
        __init__.py
        Indicator.py
        Indicator_utils.py
        -> atmos/
        -> land/
        -> seaIce/
    -> indices/
        __init__.py
        indices_utils.py
        _multivariate.py
        _simple.py
        _threshold.py
        _fwi.py
    -> decorators/
        __init__.py
        validation.py
        transformation.py
    generic.py
    utils.py
    ...
```

This proposal is open to modification/debate. I personally am not sold on `<modulename>_utils.py` and would be happier with `utils.py` within the module, but this is more to encourage a cleaner API. 

Decisions taken here will impact further refactoring efforts for milestone 0.15.0 and subsequently `finch` so this can be considered an immediate priority.

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #374
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 

This does a complete reorganization of the files in xclim, following the code review discussions.

* **Does this PR introduce a breaking change?** 

Yes, many. I made `atmos`, `land`, `seaIce` and `ICCLIM` accessible through the top level as before. But everything else moved.
The `utils.py` files was split in many other files. This breaks everything outside the indicators, the indices, ensembles or subset.

* **Other information**:

This was made from the `metadata-internationalization` branch to ease merging.

### CODE REVIEW

**Comment by aulemahal** [comment]
Sorry everyone. The initial commit of this PR was as planned in #374, but had cyclic-imports problems. The top-level initial import of indicators.atmos which imports other stuff in xclim.indicators was the culprit. 
I moved all indicator _utilities_ to a `core` submodule and left only the definition of the indicators themselves in `indicators`. 
In the `indices` submodule, I moved `calendar` to `core.calendar` and  `utils` which I merged with `core.utils`. Do we want to also move  `run_length` and `generic` to `core`?

**Comment by aulemahal** [comment]
The new structure is:
```
xclim
├── core
│   ├── calendar.py
│   ├── checks.py
│   ├── formatting.py
│   ├── indicator.py
│   ├── units.py
│   └── utils.py
├── indicators
│   ├── atmos
│   │   ├── __init__.py
│   │   ├── _precip.py
│   │   └── _temperature.py
│   ├── land
│   │   ├── __init__.py
│   │   └── _streamflow.py
│   ├── seaIce
│   │   ├── __init__.py
│   │   └── _seaice.py
│   └── __init__.py
├── indices
│   ├── __init__.py
│   ├── _multivariate.py
│   ├── _simple.py
│   ├── _threshold.py
│   ├── fwi.py
│   ├── generic.py
│   └── run_length.py
├── locales
│   ├── fr.json
│   └── __init__.py
├── testing
│   └── __init__.py
├── __init__.py
├── ensembles.py
└── subset.py
```

**Comment by aulemahal** [comment]
Thanks!
However, I don't see errors when building the docs and git says that everything is up-to-date with the master. Maybe you are missing 1 or 2 commits?

**Comment by huard** [comment]
Old unversioned files laying around are the explanation for the doc build errors.

**Comment by aulemahal** [comment]
Then LGTM, I assume @tlogan2000  approves ;).

**Comment by tlogan2000** [comment]
good

**Pull request merged**
