### PR TITLE
Add a .zenodo.json config and a CFF file

### LINKED ISSUE #721: Make xclim more FAIR
Possibly add 
- richer software metadata (see https://codemeta.github.io/)
- citation information (see https://citation-file-format.github.io/)

### References
- https://www.sciencedirect.com/science/article/pii/S2666389921000362?via%3Dihub
- https://content.iospress.com/articles/data-science/ds190026

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #721 
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (major / minor / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 

Adds a CFF file and a Zenodo configuration file. Lots of missing information still (mostly ORCID info). I'm unsure if names should priority reflect user metadata for searchability. If so, then those that haven't set a first and last name will not have their real names associated with the library. Thoughts?

* **Does this PR introduce a breaking change?** 

Only for our Zenodo citation. We need to be very certain that we're happy with it, as once we publish, we can't (shouldn't) be modifying any DOI information after publishing a new version (bad practice).

* **Other information**:

https://citation-file-format.github.io/

### CODE REVIEW

**Comment by huard** [comment]
What are the best practices for authors? I feel that including every contributor is overkill. Also, we want to be able to update that list to reflect future meaningful contributions. I suggest we draw a line - somewhere -.

**Review by aulemahal — APPROVED** [review]
Nice!
Maybe we could automate the update of the version in the CFF file with bumpversion?

Relating to the problem with linking the up-to-date zenodo, maybe a compromise solution would be to put the generic doi : "10.5281/zenodo.2795043"?  As it always point to the most recent version, this could be a problem...

Also, would : https://github.com/citation-file-format/cffconvert-github-action be useful?

**Comment by aulemahal** [comment]
>  I feel that including every contributor is overkill.

The main citation method for xclim, Zenodo, already lists everyone, ordered by commit number.  So, the CFF at least lists the same people? I agree that it could be interesting to reduce this list for the sake of readability, but at the same time, most citations will look like "XXXXX et al." anyway?

**Comment by Zeitsperre** [comment]
> What are the best practices for authors? I feel that including every contributor is overkill. Also, we want to be able to update that list to reflect future meaningful contributions. I suggest we draw a line - somewhere -.

I pulled this list and ordering (making @tlogan2000 the first author) from Zenodo. The same people are listed beyond that. The only major departure I've made is using some real names of people. In the case of @sbiner, I don't imagine him taking issue. For one-time contributors, maybe I should revert to the names found on Zenodo.

**Comment by aulemahal** [comment]
Just thought of this, @Zeitsperre, could we add a "How to cite" section in the doc? May be in the "credits" page? Also, this could be in the main README?

**Comment by Zeitsperre** [comment]
> Just thought of this, @Zeitsperre, could we add a "How to cite" section in the doc? May be in the "credits" page? Also, this could be in the main README?

This raises the question of how we want to cite our library. Are we the `Ouranos - xclim development team` or individual authors? Zenodo suggests listing the first few authors and ending with the last contributor's GitHub handle for good measure. How extensive do we want to be?

**Comment by aulemahal** [comment]
Hum, my reflex would be to go with what Zenodo does, as others do... Until we have something in JOSS. We could also use the Earthcube Meeting's citation (which are not yet published, but soon).

**Comment by Zeitsperre** [comment]
@huard I think it would be good to try and get this merged in the next version. Thoughts?

**Review by huard — APPROVED** [review]

**Pull request merged**
