### PR TITLE
Better lazy_indexing - Fix #470

### LINKED ISSUE #470: ANUCLIM calls to lazy_indexing failing
* xclim version: '0.17.1-beta'
* Python version:Python 3.7.6
* Operating System: Linux

### Description
Calculating anuclim indices on real data failing for those relying on `lazy_indexing`,   
### What I Did

```
from xclim import anuclim as anu
from xclim import indices as xci
import xarray as xr
from pathlib import Path
from xclim import subset
source = Path('data_monthly')
ncfiles = []
for v in ['tasmax','tasmin','pr']:
    ncfiles.append(sorted(list(source.rglob(f'*{v}*.nc'))))
ds = xr.open_mfdataset(ncfiles, chunks=dict(time=12), combine='by_coords')
ds =subset.subset_bbox(ds, lon_bnds=[-120, -60], lat_bnds=[47, 79], start_date='1955')
ds.pr.attrs['units'] = 'mm month-1'
ds['tas'] = 0.5*(ds.tasmax + ds.tasmin)
ds['tas'].attrs = ds.tasmax.attrs
ds['tas'].attrs['long_name'] = 'Monthly average temperature'
dsOut['P8_MeanTempWettestQuarter'] = anu.P8_MeanTempWettestQuarter(tas=ds.tas,
                                                                   pr=ds.pr,
                                                                   input_freq='monthly', freq='YS')
```

### What I Received

```
....

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "W:/Projets/Biodiversite/Humphries/Climate_indices/Calculate_climate_indices.py", line 48, in <module>
    input_freq='monthly', freq='YS')
  File "C:\Anaconda\envs\xclim\lib\site-packages\xclim\indicators\__init__.py", line 179, in _wrapper
    return func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-93>", line 2, in tg_mean_wetdry_quarter
  File "<boltons.funcutils.FunctionBuilder-44>", line 2, in tg_mean_wetdry_quarter
  File "C:\Anaconda\envs\xclim\lib\site-packages\xclim\core\units.py", line 361, in wrapper
    out = func(*args, **kwargs)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xclim\indices\_anuclim.py", line 287, in tg_mean_wetdry_quarter
    out = _from_other_arg(criteria=pr_qrt, output=tas_qrt, op=xr_op, freq=freq)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xclim\indices\_anuclim.py", line 521, in _from_other_arg
    return ds.resample(time=freq).map(get_other_op)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xarray\core\resample.py", line 304, in map
    combined = self._combine(applied)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xarray\core\groupby.py", line 954, in _combine
    applied_example, applied = peek_at(applied)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xarray\core\utils.py", line 182, in peek_at
    peek = next(gen)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xarray\core\resample.py", line 303, in <genexpr>
    applied = (func(ds, *args, **kwargs) for ds in self._iter_grouped())
  File "C:\Anaconda\envs\xclim\lib\site-packages\xclim\indices\_anuclim.py", line 519, in get_other_op
    return lazy_indexing(ds.output, index=op(ds.criteria, dim=dim), dim=dim)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xclim\indices\run_length.py", line 745, in lazy_indexing
    dask="allowed",
  File "C:\Anaconda\envs\xclim\lib\site-packages\xarray\core\computation.py", line 1064, in apply_ufunc
    keep_attrs=keep_attrs,
  File "C:\Anaconda\envs\xclim\lib\site-packages\xarray\core\computation.py", line 233, in apply_dataarray_vfunc
    result_var = func(*data_vars)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xarray\core\computation.py", line 604, in apply_variable_ufunc
    result_data = func(*input_data)
  File "C:\Anaconda\envs\xclim\lib\site-packages\xclim\indices\run_length.py", line 737, in _isel
    return np.take_along_axis(array, indx[..., None], -1)[..., 0]
  File "<__array_function__ internals>", line 6, in take_along_axis
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\array\core.py", line 1354, in __array_function__
    return handle_nonmatching_names(func, args, kwargs)
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\array\core.py", line 1339, in handle_nonmatching_names
    args, kwargs = compute(args, kwargs)
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\threaded.py", line 81, in get
    **kwargs
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*args2)
  File "C:\Anaconda\envs\xclim\lib\site-packages\toolz\functoolz.py", line 488, in __call__
    ret = f(ret)
  File "C:\Anaconda\envs\xclim\lib\site-packages\dask\array\reductions.py", line 920, in nanarg_agg
    raise ValueError("All NaN slice encountered")
ValueError: All NaN slice encountered

```

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #470 
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 
1) The error in #470 was coming from all-nan slices failing in `np.nanargmax`. This modifies the `_from_other_arg` so that  all-nan slices are first filled with 0, then masked back on the result.

2) Not directly in #470, but that issue shows that `lazy_indexing` was not lazy.  Dask doesn't implement `np.take_along_axis` (yet) . I modified the whole function using the same code as in `xr.DataArray.idxmax`. We are pretty much doing the exact same as this function, but it's not yet released.

### CODE REVIEW

**Comment by aulemahal** [comment]
I copied code from xarray for this, assuming they would have tested that part... Turns out there is a bug...

**Comment by aulemahal** [comment]
I believe this is fixed! (Collateral damage: pydata/xarray#4135)

**Comment by aulemahal** [comment]
Reverted back to the initial option for lazy_indexing. This adds the constraint that the data cannot be chunking along "time", so I added some chunking management for anuclim indices.

**Comment by tlogan2000** [comment]
I think we've got it.  running ok on my end

**Pull request merged**
