### PR TITLE
Glob-like patterns in AttrFormatter and french nouns

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes an issue raised in slack.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 
Values to format, in `core.formatting.AttrFormatter` can now include glob-like patterns. Example : `"QS-*`" that translates to "seasonal".

* **Does this PR introduce a breaking change?** 
No

* **Other information**:
Also added the plural nouns in french. I don't think we're using them, but they exist in the english formatter.

### CODE REVIEW

**Review by tlogan2000 — CHANGES_REQUESTED** [review]
Builds are failing on this

**Comment by Zeitsperre** [comment]
The doctests are failing on the style of guillemets. That's annoying. Looking into this.

**Comment by Zeitsperre** [comment]
Opened an issue about it. You may need to change your string quotations in the meantime. https://github.com/Erotemic/xdoctest/issues/87

**Comment by aulemahal** [comment]
Oh easy fix. I will use «» instead.

**Comment by aulemahal** [comment]
Sooo, the first doctext uses " and the second one ' ? Some magic is happening here...

**Comment by Zeitsperre** [comment]
The maintainer of xdoctest is open to a PR to implement a means to relax this feature, but this wacky behaviour exists in the stdlib doctest as well. He mentioned using `...` if you want to evade the quotation mark problem altogether.

**Review by tlogan2000 — APPROVED** [review]
Assuming docs build correctly i approve in advance

**Comment by aulemahal** [comment]
The stalled and failed RTD build is not updating here in github? Anyway, I tested this branch on RTD directly and it worked. Merging.

**Pull request merged**
