### PR TITLE
Use latest `pytest` and `xdoctest`

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR closes #1631 
- [x] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGES.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Unpins the `pytest` version now that `xdoctest` supports it.
* Pins to the latest `xdoctest` supporting `pytest~=8.0`.

### Does this PR introduce a breaking change?

No.

### Other information:

FYI @RondeauG 

The newest `pytest` (v8.0.0) introduced some regressions for Windows users. An issue is already up and a patch should arrive shortly (https://github.com/pytest-dev/pytest/issues/11895). Until then, use `pytest<8.0` on Windows.

See also: https://github.com/pytest-dev/pytest/issues/11969

### CODE REVIEW

**Comment by Zeitsperre** [comment]
The conda package is not yet available. Will re-run CI in a bit.

**Review by aulemahal — APPROVED** [review]

**Comment by Zeitsperre** [comment]
Looks like my namespace hack isn't working. I'll need to return to this next week.

**Comment by Zeitsperre** [comment]
The latest pytest (v8.0.0) seems to have broken the conventional approach for injecting commands into the doctest namespace (used in the doctests). 

Waiting to see what happens in https://github.com/pytest-dev/pytest/issues/11929

**Comment by Zeitsperre** [comment]
This functionality has been borked with 8.0.0 (See: https://github.com/pytest-dev/pytest/issues/11873). No way of upgrading until a fix arrives.

**Comment by Zeitsperre** [comment]
The issue persists: https://github.com/pytest-dev/pytest/issues/11884

**Comment by Zeitsperre** [comment]
This has been quite a day.

burn-elmo

**Review by aulemahal — APPROVED** [review]
Looks good!

**Pull request merged**
