### PR TITLE
Fix 616

### LINKED ISSUE #616: Adapt test ensemble to support sklearn v0.24.0
* xclim version: master

### Description

`scikit-learn` released a new minor version (https://pypi.org/project/scikit-learn/) over the holidays, and it's breaking tests.

### What I Did

```
$ tox
```

### What I Received

```
xclim/testing/tests/test_ensembles.py:215 (TestEnsembleReduction.test_kmeans_rsqcutoff)
[0, 1, 3, 4, 6, 7, 8, 10, 11, 15, 18, 20, 22] != [0, 1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 15, 20, 22]

Expected :[0, 1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 15, 20, 22]
Actual   :[0, 1, 3, 4, 6, 7, 8, 10, 11, 15, 18, 20, 22]
<Click to see difference>

self = <xclim.testing.tests.test_ensembles.TestEnsembleReduction object at 0x7fcc8c144910>

    def test_kmeans_rsqcutoff(self):
        pytest.importorskip("sklearn", minversion="0.22")
        ds = open_dataset(self.nc_file)
    
        # use random state variable to ensure consistent clustering in tests:
        [ids, cluster, fig_data] = ensembles.kmeans_reduce_ensemble(
            data=ds.data, method={"rsq_cutoff": 0.9}, random_state=42, make_graph=False
        )
    
>       assert ids == [0, 1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 15, 20, 22]
E       assert [0, 1, 3, 4, 6, 7, 8, 10, 11, 15, 18, 20, 22] == [0, 1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 15, 20, 22]

xclim/testing/tests/test_ensembles.py:225: AssertionError
...
xclim/testing/tests/test_ensembles.py:238 (TestEnsembleReduction.test_kmeans_rsqopt)
[3, 4, 5, 7, 10, 11, 12, 13] != [4, 5, 7, 10, 11, 12, 13]

Expected :[4, 5, 7, 10, 11, 12, 13]
Actual   :[3, 4, 5, 7, 10, 11, 12, 13]
<Click to see difference>

self = <xclim.testing.tests.test_ensembles.TestEnsembleReduction object at 0x7fcc857a5940>

    def test_kmeans_rsqopt(self):
        pytest.importorskip("sklearn", minversion="0.22")
        ds = open_dataset(self.nc_file)
        [ids, cluster, fig_data] = ensembles.kmeans_reduce_ensemble(
            data=ds.data,
            method={"rsq_optimize": None},
            random_state=42,
            make_graph=False,
        )
>       assert ids == [4, 5, 7, 10, 11, 12, 13]
E       assert [3, 4, 5, 7, 10, 11, 12, 13] == [4, 5, 7, 10, 11, 12, 13]

xclim/testing/tests/test_ensembles.py:248: AssertionError
...
xclim/testing/tests/test_ensembles.py:311 (TestEnsembleReduction.test_kmeans_variweights)
self = <xclim.testing.tests.test_ensembles.TestEnsembleReduction object at 0x7fcc8c14b790>

    def test_kmeans_variweights(self):
        pytest.importorskip("sklearn", minversion="0.22")
        ds = open_dataset(self.nc_file)
        # Test sample weights
        var_weights = np.ones(ds.data.shape[1])
        # reduce weights for some variables
        var_weights[3:] = 0.25
    
        [ids, cluster, fig_data] = ensembles.kmeans_reduce_ensemble(
            data=ds.data,
            method={"rsq_cutoff": 0.9},
            random_state=42,
            make_graph=False,
            variable_weights=var_weights,
        )
        assert ids == [1, 3, 8, 10, 13, 14, 16, 19, 20]
        assert len(ids) == 9
    
        # using RSQ optimize
        [ids, cluster, fig_data] = ensembles.kmeans_reduce_ensemble(
            data=ds.data,
            method={"rsq_optimize": None},
            random_state=42,
            make_graph=False,
            variable_weights=var_weights,
        )
    
        assert ids == [2, 4, 8, 13, 14, 22]
        assert len(ids) == 6
    
        # try zero weights
        var_weights = np.ones(ds.data.shape[1])
        var_weights[[1, 4]] = 0
    
        [ids, cluster, fig_data] = ensembles.kmeans_reduce_ensemble(
            data=ds.data,
            method={"rsq_optimize": None},
            random_state=42,
            make_graph=False,
            variable_weights=var_weights,
        )
        # Results here may change according to sklearn version, hence the *isin* intead of ==
>       assert all(np.isin([4, 12, 13, 16], ids))
E       assert False
E        +  where False = all(array([False,  True,  True,  True]))
E        +    where array([False,  True,  True,  True]) = <function isin at 0x7fccbdf04430>([4, 12, 13, 16], [8, 11, 12, 13, 16, 20])
E        +      where <function isin at 0x7fccbdf04430> = np.isin

xclim/testing/tests/test_ensembles.py:354: AssertionError
```

### PR DESCRIPTION
**Pull request by tlogan2000**
### Pull Request Checklist:
- [X] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #616
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [x] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 
bug fix

* **Does this PR introduce a breaking change?** 
no

* **Other information**:

### CODE REVIEW

**Comment by tlogan2000** [comment]
tox build is failing for subset... possibly my clisops not updated to latest... 

Ensembles tests seem fine. 
note tox build for py 3.8 only for now. maybe a friendly reviewer could run again?

**Comment by aulemahal** [comment]
May I add  fix for the other tests here? `subset_shape` and `py36-xarray` mostly.

**Comment by tlogan2000** [comment]
> May I add fix for the other tests here? `subset_shape` and `py36-xarray` mostly.

of course

**Review by Zeitsperre — APPROVED** [review]
More general, should cause fewer headaches

**Comment by aulemahal** [comment]
All tests work, except : py39 and py37-bottleneck, but that's only because of my configuration.

**Pull request merged**
