### PR TITLE
New testing.open_dataset method for downloading test data

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR goes in the direction of fixing #525.
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [x] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 
Adds `open_dataset` to  xclim.testing. Both are copied and adapted from xarray, with the following changes:
    - Use of pathlib instead of os
    - Allow sub-folders in the distant repo.
    - Change default parameters to point to xclim-tesdata.

* **Does this PR introduce a breaking change?** 
No

Tests are coming when the structure of xclim-testdata is updated.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@aulemahal Problematic testing case: `test_ensembles.py`

```
class TestEnsembleStats:
    nc_files_simple = glob.glob(
        os.path.join(TESTS_DATA, "EnsembleStats", "*1950-2100*.nc")
    )
    nc_files = glob.glob(os.path.join(TESTS_DATA, "EnsembleStats", "*.nc"))
```

We may need to hardcode these files and then open them before sending them to `create_ensemble()`. What do you think?

**Comment by aulemahal** [comment]
Yuck... We could also create the ensemble beforehand and have it as a netcdf in the repo?

**Comment by Zeitsperre** [comment]
There's a few instances of `xr.open_mfdataset()` in our testing ensemble. Is this possible or would it be better to `concat` opened `Datasets` ?

**Comment by aulemahal** [comment]
Unless the thing tested is the multiplicity of the files, I believe the next test clean up step will remove those calls.  For now, we could indeed concat opened datasets?
As for tests where multiple files is important (like for `xclim.ensembles` I presume), I'm not sure of the way forward...

**Comment by Zeitsperre** [comment]
@aulemahal There seems to be an issue with the FWI Indices tests. It could be that the assertion is not an exact match. Barring the `open_mfdataset` and `create_ensemble` tests, everything is coming together. Could likely finish this today.

**Comment by aulemahal** [comment]
I'll look into the FWI problem.
Also, in regard to your last commit, would it be possible to reactivate the windows test build on this PR? I don't think windows users should have to use `os.path.join` to use `testing.open_dataset`. I'll try to think of a workaround, but would be interested to see the CI build!

**Comment by Zeitsperre** [comment]
> Also, in regard to your last commit, would it be possible to reactivate the windows test build on this PR? I don't think windows users should have to use `os.path.join` to use `testing.open_dataset`. I'll try to think of a workaround, but would be interested to see the CI build!

Yeah, I can re-enable it, but it'll need to be deactivated again before pushing to master. The other option is to use `Path` objects; they are able to determine OS-specific path names as well.

**Comment by aulemahal** [comment]
Easier than I thought!

**Comment by Zeitsperre** [comment]
We just need to revert https://github.com/Ouranosinc/xclim/commit/f23f2f32f1ae221c1e57d3effec7b8339b7a1980 and we're good, I think!

**Review by huard — APPROVED** [review]

**Pull request merged**
