### PR TITLE
Reduce circular imports in xclim.core

### LINKED ISSUE #949: Circular imports
### Description

`core.missing` imports `indices.generic`, while some indices import `core.missing`, which causes circular import problems. 

The function required in `core.missing` is `select_time`. I suggest it is moved somewhere in `core/`, e.g. utils.py.

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #949 
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.
- [x] `bumpversion patch` has been called on this branch
- [ ] The relevant author information has been added to `.zenodo.json`

### What kind of change does this PR introduce?

* Moved `select_time` to `calendar.py`.
* Added an `__all__` section in `calendar.py`.
* Specified more relative imports within `xclim.core`.
* Flag a DeprecationWarning when calling `select_time` from `xclim.indices.generic`.
* Cleaned up a few imports in `xclim.testing.tests.test_generic.py`.
* Removed some imported but unused functions throughout the library modules.

### Does this PR introduce a breaking change?
Yes. `select_time` is now found at `xclim.core.calendar`. A DeprecationWarning is now shown when accessing `select_time` from `xclim.indices.generic`.

### CODE REVIEW

**Comment by aulemahal** [comment]
Sorry to be that guy, but I'm still not convinced that there were serious circular imports issues. And I think this PR supports my point : to solve the issue you here moved the core "calendar" functions outside of the "calendar" module. This is a much heavier move than simply importing `select_time` from within the functions that used it outside of `xclim.indices`. If  `select_time` can't be moved outside of `generic` without such a large _dérangement_,  I vote against moving it at all. Otherwise, I agree that `select_time` is the generic-est of the indices and thus it can makes sense to move it to `utils.py`.

**Comment by Zeitsperre** [comment]
That's absolutely fair. To be honest, I'm a bit surprised by the amount of changes needed, but otherwise we end up creating actual circular imports. My strategy was to make `utils.py` the base that would be referred to within `xclim.core`, but I can probably simply move `select_time` there if we're fine with _some_ redundancy (hopefully not copied functions).

Should I open a new PR or modify this one?

**Comment by aulemahal** [comment]
I'm ok with editing this PR (worst case we'll squash and merge).
Thanks!

**Review by aulemahal — APPROVED** [review]
`select_time` in calendar.py, makes perfect sense! Thanks!

**Pull request merged**
