### PR TITLE
bugfix: remove space in freq default.

### PR DESCRIPTION
**Pull request by huard**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated

### After merging to master and before closing the branch:
- [ ] bumpversion (minor / major / patch) has been called on `master` branch
- [ ] Tags have been pushed

* **What kind of change does this PR introduce?** 
Bug fix.

### CODE REVIEW

**Comment by huard** [comment]
Our test suite has a problem if it does not catch that kind of thing. I'll open a ticket.

**Comment by Zeitsperre** [comment]
Ouch. That's an oversight. I think most all of our test show us explicitly calling function with all signatures set, which isn't how users might use the library. Maybe the jupyter notebook approach would be a way of satisfying both showing the use cases and simultaneously testing for use cases that might be employed.

**Comment by Zeitsperre** [comment]
Issue a hotfix?

**Comment by huard** [comment]
Yep, again, I need a tag for Finch, and this breaks at "import finch"...

**Pull request merged**
