### PR TITLE
Pin Tox and re-enable conda-tox in workflows

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Pins tox at v3 due to some really breaking bugs in the current version (released last week).
* Re-enables the conda-tox build using tox at v3
* fixes a broken link to a PDF in our references
* updates a notebook that made mention of an obsolete module

### Does this PR introduce a breaking change?

No. It fixes something that was breaking.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
This good for review!

**Review by aulemahal — APPROVED** [review]
Looks like a good (temporary ?) fix to me! Thanks!

**Comment by aulemahal** [comment]
As I see the HDF Error is back, I suggest we remove the `git clone` line in `tox.ini`, as it didn't really solve it. We were simply lucky I guess.

**Comment by aulemahal** [comment]
I have no idea if this is related, but I noticed that we download the MD5 file even if the netCDF file already exists:
https://github.com/Ouranosinc/xclim/blob/939adcf46df944dd16d601b10cd3825cddccdf1c/xclim/testing/utils.py#L189-L196

This means we are still writing to disk each time `open_dataset` is called. Maybe there some non-thread-safe things happenning? (I have no idea how it could resolve in a HDF error though).

We could try to:
- Download the MD5 to memory instead than to a file?
- Use locks to prevent multiple write attemps.
?

**Comment by Zeitsperre** [comment]
The thread problem is still there, but at least we have something that errors out LESS. I fear that the only way to fix this is to completely throw out most of the file gathering tools for `pooch`, and I don't want to do that just yet.

Will update history and merge.

**Pull request merged**
