### PR TITLE
Remove faulty default in MRT and UTCI

### LINKED ISSUE #1496: NA values for UTCI - issue with mean radiant temperature calculations?
### Setup Information

- Xclim version: 0.41.0
- Python version: 3.10.10
- Operating System: macOS 12.6.7

I'm calculating UTCI for Southeast Asia and noticed that there are quite a lot of NA values, but this varies spatially and temporally, for parts of the year the northern hemisphere in Southeast Asia has missing values, and other parts of the year the southern hemisphere in Southeast Asia has missing values (see attached screenshots). Could this be due an issue with the mean radiant temperature, as it is influenced by latitude? There's a clear cutoff at the equator.

Screenshot 2023-10-10 at 11 36 53
Screenshot 2023-10-10 at 11 36 40

### Context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #1496
- [x] Tests for the changes have been added (for bug fixes / features)
  - [x] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGES.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?
I believe #1399 changed the meanings of argument `stat` which made the default option of `mean_radiant_temperature` incorrect. This PR removes the "average" option and changes the default to 'sunlit'.

### Does this PR introduce a breaking change?
Yes, outputs will change. However, I think previous output was incorrect. An announcement has been added to the CHANGES.

### CODE REVIEW

**Review by Zeitsperre — APPROVED** [review]
LGTM

**Comment by ludwiglierhammer** [comment]
I think this should be adopted to UTCI as well, isn't it?

**Comment by Zeitsperre** [comment]
@emsonali

Hi there, we're preparing a new release of xclim no later than tomorrow. If you have a minute, please let us know if this PR settles the issue you were experiencing with the MRT index. Thanks!

**Comment by emsonali** [comment]
Hi @Zeitsperre, thanks for the update. I've tested the fix and have updated @aulemahal on the other thread. I just need him to verify if one of the stat settings is working as expected. Following his response, you can proceed.

**Pull request merged**
