### PR TITLE
Fix 263new

### LINKED ISSUE #263: Implement ensemble reduction selection algorithms
- [ ] implement Ouranos K-means clustering method for reducing ensemble size (see https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0152495)

- [ ] Optionally implement KKZ method (PCIC) see https://journals.ametsoc.org/doi/full/10.1175/JCLI-D-14-00636.1

### PR DESCRIPTION
**Pull request by tlogan2000**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated

### After merging to master and before closing the branch:
- [ ] bumpversion (minor / major / patch) has been called on `master` branch
- [ ] Tags have been pushed

* **What kind of change does this PR introduce?** 
Adds k-means clustering ensemble size reduction  see #263

* **Does this PR introduce a breaking change?** 
No 

* **Other information**:

This PR fixes #263 (kmeans only)

### CODE REVIEW

**Comment by tlogan2000** [comment]
Note:This is just a test to see if builds pass will push to official 'fix_263' if all is ok

**Comment by tlogan2000** [comment]
The new xarray v0.14.0 is breaking utils.percentile_doy()'s  grouby,reduce() call - bug fix coming : see https://github.com/pydata/xarray/issues/3402.  

The new version also seems to break ensembles.create_ensemble() but this I have managed to fix it (should work in 0.13.0 as well)

We could possibly pin the xarray version to 0.13.0 while waiting for the bug fix to appear on pypi?Opinions? @Zeitsperre @huard

**Comment by Zeitsperre** [comment]
I can go forward with this and tag the release as 0.11.

**Comment by tlogan2000** [comment]
I've got a few more changes to push ....

**Comment by tlogan2000** [comment]
@huard can you confirm that this addresses your comments in https://github.com/Ouranosinc/xclim/pull/264?  Sorry for the hassle but the original fix_263 branch is really messed up and I seem unable to push these additions/mods without wasting a bunch of time

**Comment by huard** [comment]
Do you need this soon ? I can only take a cursory look before Nov 11. 
I spotted a couple of syntax issues in the docstrings. 
My main issue were the graphics, which is now fixed. I suggest you don't wait for my review and go ahead with the merge. An upcoming task anyway is to create an "Ensemble" class, and I expect that clustering could be a method from that class, which will give us a chance to do some further refactoring if needed.

**Pull request merged**
