### PR TITLE
Data quality assurance checks

### LINKED ISSUE #65: Quality control checks
### Description

ICCLIM performs quality control checks on input data depending on the variable. This is something we could add to XCLIM. 

See chapter 3 of [ICCLIM docs](https://eca.knmi.nl/documents/atbd.pdf)

### daily precipitation amount RR:
- [x] must be equal or exceed 0 mm
- [x] must be less than 300.0 mm
- [x] must not be repetitive (i.e. exactly the same amount) for 10 days in a row if amount larger than 1.0 mm
- [x] must not be repetitive (i.e. exactly the same amount) for 5 days in a row if amount larger than 5.0 mm
- [ ] dry periods receive flag = 1 (suspect), if the amount of dry days lies outside a 14·bivariate standard deviation

### daily maximum temperature TX:
- [x] must exceed -90.0 ◦ C
- [x] must be less than 60.0 ◦ C
- [x] must exceed or equal daily minimum temperature (if exists)
- [x] must exceed or equal daily mean temperature (if exists)
- [x] must not be repetitive (i.e. exactly the same) for 5 days in a row
- [x] must be less than the long term average daily maximum temperature for that calendar day + 5 times standard deviation (calculated for a 5 day window centered on each calendar day over the whole period)
- [x] must exceed the long term average daily maximum temperature for that calendar day - 5 times standard deviation (calculated for a 5 day window centered on each calendar day over the whole period)

### Daily minimum temperature TN:
- [x] must exceed -90.0 ◦ C
- [x] must be less than 60.0 ◦ C
- [x] must be less or equal to daily maximum temperature (if exists)
- [x] must be less or equal to daily mean temperature (if exists)
- [x] must not be repetitive (i.e. exactly the same) for 5 days in a row
- [x] must be less than the long term average daily minimum temperature for that calendar day + 5 times standard deviation (calculated for a 5 day window centered on each calendar day over the whole period)
- [x] must exceed the long term average daily minimum temperature for that calendar day - 5 times standard deviation (calculated for a 5 day window centered on each calendar day over the whole period)

### Daily mean temperature TG:
- [x] must exceed -90.0 ◦ C
- [x] must be less than 60.0 ◦ C
- [x] must exceed or equal daily minimum temperature (if exists)
- [x] must be less or equal to daily maximum temperature (if exists)
- [x] must not be repetitive (i.e. exactly the same) for 5 days in a row
- [x] must be less than the long term average daily mean temperature for that calendar day + 5 times standard deviation (calculated for a 5 day window centered on each calendar day over the whole period)
- [x] must exceed the long term average daily mean temperature for that calendar day - 5 times standard deviation (calculated for a 5 day window centered on each calendar day over the whole period)

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated

### After merging to master and before closing the branch:
- [ ] bumpversion (minor / major / patch) has been called on `master` branch
- [ ] Tags have been pushed

* **What kind of change does this PR introduce?** 
This PR adds several quality assurance checks for data values when loading NetCDF files based on the checks employed by libraries like ICCLIM.

* **Does this PR introduce a breaking change?** 
Potentially. Depending on the severity of the warnings, data that does not adhere to ICCLIM-like sanity checks may raise errors. Raising errors should be marked optional by default.

* **Other information**:

This PR fixes #65

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@huard Could you explain the logic behind the condition flags for validating the DataArrays. Where do the conditions classes come in?

**Comment by huard** [comment]
See https://eca.knmi.nl/documents/atbd.pdf
Page 10, Chapter 3. Quality control

This is what I've been trying to emulate. Unclear yet how to hook this into xclim.

**Comment by Zeitsperre** [comment]
I should have been clearer in my question, I'm more wondering about the hook method. Maybe there's a way to perform a class composition?

**Comment by huard** [comment]
I haven't thought about that in a long while. I'm not sure we should integrate it right into indicators. If we run multiple indicators on the same variable, it would be a waste of CPU to re-run the compliance suite every time. It might be smarter to have a standalone function or class doing this, and the user would have to explicitly integrate those checks into their workflows. 

That being said, we still need to think about how to build some flexibility into that compliance test function, to allow users to add or remove some checks.

**Comment by huard** [comment]
After refactoring in #435, this could go into `datachecks.py`.

**Comment by Zeitsperre** [comment]
Closing this PR in favour of #645

**Pull request closed without merging**
