### PR TITLE
Add xdoctest

### LINKED ISSUE #450: Not all doctests are picked by pytest
### Description

- Not all doctests in docstrings are picked up by pytest.
- I don't think code in the docs is exercised by pytest yet.

For example, in `indices`, `max_n_day_precipitation_amount` runs, but not `max_1day_precipitation_amount`.

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #450 
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
- [x] `bumpversion (minor / major / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 

This PR adds the [`xdoctest`](https://github.com/Erotemic/xdoctest) library to the dev build and implements it in the tox builds that check the documentation. This library uses a much better parser and is able to find all the documentation examples within the code and properly run evaluation tests on them.

I've also reformatted many docstrings that simply weren't being formatted properly on ReadTheDocs. Consequently, locally-building the docs via `make docs` at the top-level now raises MANY warnings that should eventually be addressed.

Another problem relates to discussion in #506. I have elected to set all tests that only marginally pass to be skipped entirely. If we can figure out how best to deal with the example test data problem, we can re-enable these checks.

* **Does this PR introduce a breaking change?** 

No, though docstring standards are getting generally stricter.

* **Other information**:

I've made the decision to import global and locally-imported libraries within the examples to show users how to gain access to the functions being presented. This is more of a stylistic decision, and we can discuss whether we like examples to be short and sweet or longer and more elaborate, albeit more redundant.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@tlogan2000 Would this check be something that we want as a build failure? Badly-written or error-filled examples could prevent new merges? What say you?

**Comment by tlogan2000** [comment]
> @tlogan2000 Would this check be something that we want as a build failure? Badly-written or error-filled examples could prevent new merges? What say you?

i.e any new examples moving forward ?  I would say yes but we would need to create a standard dataset to run to docs right?

**Comment by Zeitsperre** [comment]
Precisely. That's more or less what #506 is about. 

I'll add the "doctests and linting" build as another check entirely (that runs `pylint` in no-failures mode so that we can see what should be addressed without blocking merges due to "errors"). 

Linting errors are more like very strong code suggestions that will take time to deal with and will need some serious digging and debate, and potentially some refactoring as well. Best to deal with in another issue/PR.

**Comment by tlogan2000** [comment]
ok for me

**Pull request merged**
