### PR TITLE
Add `q` (streamflow) to variables.yml

### PR DESCRIPTION
**Pull request by coxipi**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGELOG.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Add `q` as a proper variable in variables.yml

### Does this PR introduce a breaking change?

No

### Other information:

Discussing with @RondeauG , we were deliberating between `qstr`, `qstrm`, `strf`. I haven't seen any of these variables in many places in litterature, there doesn't seem to be a standard abbreviation apart from `Q` or `q` (flow or specific flow ), so I'm enclined to change `strf` if it doesn't feel right.

### CODE REVIEW

**Comment by aulemahal** [comment]
But if `q` _is_ the most common standard, why would we not use that ?

**Comment by coxipi** [comment]
> But if `q` _is_ the most common standard, why would we not use that ?

I just thought that the variable associated with the streamflow should have its standard naming declared with units in `variables.yml`. Then, if we define `q` as a streamflow in `variables.yml`, I'm not sure it's a good idea to use it as a variable for quantiles, no?

**Comment by aulemahal** [comment]
Most references to `q` as "quantile" I see in xclim are in `sdba`, where I would assume context is enough to make the difference ? There are no indicators that refer to quantiles as `q`, only `xc.indices.stats.parametric_quantile` does it and I would argue again that context would be enough here.

I think my point is that such a breaking change doesn't seem justified if it is not based on convention.

**Comment by coxipi** [comment]
Ok, I've just replaced the `streamflow` entry in variables.yml with `q`  then.

**Review by RondeauG — APPROVED** [review]
Sorry, I didn't see that you had requested a review from me!

**Review by Zeitsperre — APPROVED** [review]

**Pull request merged**
