### PR TITLE
Add indicator classes

### PR DESCRIPTION
**Pull request by tlogan2000**
Adding indicator Temp classes and tests (To be contiued)

### CODE REVIEW

**Comment by tlogan2000** [comment]
@huard I seem to have trouble creating dynamic 'identifier' ... e,g, adding {thresh} to gddgrow 
Any ideas why?

**Comment by huard** [comment]
Fixed. Sorry about this.

**Comment by tlogan2000** [comment]
cool .. sorry for not fixing myself. will have to learn more how the class argument work ...

**Comment by huard** [comment]
https://docs.quantifiedcode.com/python-anti-patterns/readability/not_using_dict_keys_when_formatting_strings.html#best-practice

**Pull request merged**
