### PR TITLE
Revamp CI to reduce number of builds prior to PR approved status and use pytest-xdist

### LINKED ISSUE #1155: Speed up CI checks by splitting dedicated documentation and upstream builds ?
### Addressing a Problem?

Xclim has many dependencies that are heavily tested, and runs some fairly advanced examples in the notebooks on every build. Sometimes this means CI checks run for 20+ minutes on each commit. This is a lot of computing time spent on every commit.

### Potential Solution

Assuming a pull request doesn't introduce breaking changes to the existing tools (different call signatures, different expected results, etc.), the notebooks at least should remain valid between commits and PRs. Upstream dependencies are meant for us to be aware of upcoming changes, so focused PR contributions shouldn't need to worry about this level of support.

I would like to see us using sphinx-autodoc import mocking and only running the notebooks as-needed (i.e. if breaking changes are introduced). I also think upstream dependency checks should be run on the trunk. There are a few ways that we could do this:

1. We patch `docs/conf.py` in a GitHub Action to mock imports when the branch is not `master`.
2. We investigate whether there is a way to have a toggle-able configuration within the PR that only starts building with real dependencies and running notebooks when marked.
3. (Maybe overengineered) We dedicate a `dev` branch that PRs are expected to push to. This branch will then run heavier CI tests and can be modified directly, as-needed. On success, we push to master (`latest`).

In all case, I think we should move upstream-related tests to only run on push to `master`/`dev`.

### Additional context

_No response_

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #1155 
- [x] Tests for the changes have been added (for bug fixes / features)
  - [x] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added
- [x] The relevant author information has been added to `AUTHORS.rst` and `.zenodo.json`

### What kind of change does this PR introduce?

* Changes the process in which the xclim testing suite is triggered:
   - Before Pull Request review: The `black` build and a simple Python3.8 build are triggered.
   - On "approved" Pull Request review: A new workflow "label_on_approval.yml" will add an "approved" label. This will trigger a build still starting with the `black` build, but using the full testing suite (Doctests and multiple builds of Python with reported coverage).
   - Changes made after "approved" label: The full testing suite will still be triggered on each new commit.
   - When pushed to master: The full testing suite will be triggered.
* ReadTheDocs Pull Request builds no longer rebuild the notebooks on each commit
   - When pushed to master: The full documentation is generated, including the running of notebooks.
* `pytest` now launches multiple workers (max = 6) in order to significant reduce the time needed to run the testing suite.
  - Our test fixtures needed to be more thread-aware, so this is now addressed!
* Migrates the existing GitHub CI images to use the 22.04 Ubuntu images
* Splits the docs-building steps to prevent source files from being erased and remade when running checks and docs
* Fixes a handful of broken links in the documentation.
  * `fail_on_warning` is now fully enforced
* `SKIPNOTEBOOKS` → `SKIP_NOTEBOOKS`.
* A welcome message has been added for first time PR contributors asking them to add their contact info to `AUTHORS.rst` and `.zenodo.json`

### Does this PR introduce a breaking change?

Yes. `pytest-xdist` is now a development dependency. 

### Other information:

* [pytest-xdist](https://github.com/pytest-dev/pytest-xdist)
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
* https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
* https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types
* https://docs.github.com/en/actions/learn-github-actions/expressions

* Also: https://stackoverflow.com/questions/61886993/in-github-actions-how-to-get-the-type-of-a-trigger-event-as-a-variable

### CODE REVIEW

**Comment by Zeitsperre** [comment]
ReadTheDocs build time goes from 17.5 minutes to 10 minutes when not running notebooks. Works for me.

**Review by aulemahal — APPROVED** [review]
Seems good

**Comment by Zeitsperre** [comment]
!run doctests

**Comment by Zeitsperre** [comment]
!run doctests

**Comment by Zeitsperre** [comment]
!run doctests

**Comment by Zeitsperre** [comment]
!run doctests

**Review by juliettelavoie — APPROVED** [review]
pour tester

**Comment by Zeitsperre** [comment]
@aulemahal @juliettelavoie

This Pull Request is ready for (actual) review. There are many changes to the ways that workflows are organized and triggered, but this should cut down on simultaneous builds quite a bit.

When we open Pull Requests now, we will only be testing for code style and whether it works on Python3.8. Once the PR has been approved, a label will be automatically added (`approved`), and this will trigger the more intense testing suite (this now includes the Doctests) and subsequent code coverage reports.

For build on ReadTheDocs, Pull Request builds no longer run the notebooks. They are now only generated once changes have been pushed to `master`. This cuts down time on RtD PR builds by around 7 minutes.

In terms of the builds (test-py38-upstream-lm3, test-py39-sbck-slow-conda, test-py310) I am thinking of pulling the `upstream` from the `needs` block of the `finish` step. This means that we would allow that build to fail (i.e. not blocking merge to master). I'm wondering what you think about that idea.

Thanks for the help!

**Review by aulemahal — APPROVED** [review]
Super!
I agree with removing the requirement for `upstream` to pass.

**Comment by Zeitsperre** [comment]
This PR was somewhat blown out of scope, but here's a summary of the gains:
 - ReadTheDocs builds are much faster
 - Testing prior to PR approval now finishes in under 10 minutes
 - The number of simultaneous runs after approval is reduced
 - We now run `pytest` across multiple workers to bring down the time needed to run tests
 - We now have workflows for:
   - Auto-labelling PRs as approved on approval
   - Asking first time PR contributors to add their contact info to `AUTHORS.rst` and `.zenodo.json`

Once the coveralls reporting issue is addressed (might be a website outage) this can be merged.

**Comment by Zeitsperre** [comment]
@aulemahal 

I hate to ask again, but if you have a minute to review the changes made for thread safety, I think that's all that's needed. I had to rewrite some test fixtures and move some file access steps to the fixtures as well. Essentially, I needed to ensure that at no point in time would two running processes attempt to open the same file, so we now copy the relevant files to a tempdir for each launched pytest worker on execution.

Thanks again!

**Pull request merged**
