### PR TITLE
Fix type issue in DataFlags and workaround failing notebook

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added.
- [ ] `bumpversion patch` has been called on this branch
- [ ] The relevant author information has been added to `.zenodo.json`

### What kind of change does this PR introduce?

* Addresses an undefined behaviour that was affecting dask computation of dataflags checks

### CODE REVIEW

**Comment by Zeitsperre** [comment]
Looks like one of the notebook cells is chewing up all available CPU/memory on ReadTheDocs and here
```
============================= slowest 3 durations ==============================
2000.03s call     docs/notebooks/usage.ipynb::Cell 4
83.23s call     docs/notebooks/sdba.ipynb::Cell 20
39.21s call     docs/notebooks/ensembles-advanced.ipynb::Cell 11
```

**Comment by Zeitsperre** [comment]
@aulemahal 
The cell commands in question:
```
ds6h = xr.tutorial.open_dataset("air_temperature")
gdd = xclim.atmos.growing_degree_days(ds6h.air, thresh="10.0 degC", freq="MS")
```
Very weird beahviour: in a standard Python REPL (Python3.8 + Xarray v0.21), I get what I expected:
```xclim.core.utils.ValidationError: Frequency of time series not strictly in ['D']. To mute this, set xclim's option data_validation='log'.
```
But when run on Jupyter, the cell is triggered to run and doesn't throw any errors, it just hangs. I've never seen this before.

**Comment by aulemahal** [comment]
Hum. Maybe the `tutorial.open_dataset` ? Have you tried to delete your local tutorial data (`~/xarray_tutorial_data`, or something like that) and run it locally?

**Comment by Zeitsperre** [comment]
Just tried re-running on both REPL and Jupyter, deleting my cache between runs - same results. There's something odd going on with that cell.

**Comment by aulemahal** [comment]
I'm getting mixed message from this. Your commit cafc2ec (reformat cli notebook) failed because of the error you raised here. But the next commit cacca48 (update history) fails for another seemingly unrelated reason. 
Can we simply try again? It feels like both timeouts where random.

**Comment by Zeitsperre** [comment]
Long story short - `nbstripout` has a tendency to fail when notebooks are _staged_ for commits. Since a PR that touches a notebook considers a notebook staged, we get different behaviour of pre-commit locally for a set of changes versus stages in pre-commit.ci for a full PR. The issue is known to the developer of nbstripout.

**Comment by Zeitsperre** [comment]
@aulemahal Good to merge?

**Review by aulemahal — APPROVED** [review]

**Pull request merged**
