### PR TITLE
Fix cosine of solar zenith angle glitches

### LINKED ISSUE #1110: Fix glitches in cosine_of_solar_zenith_angle
The new `cosine_of_solar_zenith_angle`, introduced in #1062, has some issues. The polar regions (with no sunset/rise) are not correctly handled and there are some glitches from unknown sources. Some are documented in the PR and should be fixable with a few corrections inspired from `PyWBGT`.

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #1110
- [x] Tests for the changes have been added (for bug fixes / features)
  - [x] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGES.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?
Refactor of the function so we can use a ufunc, making it easier to implement  the different cases.

Earlier version was not handling the cyclical nature of angles correctly and had issues in the polar regions. 

### Does this PR introduce a breaking change?
Yes, the output has changed. I think it is now correct. The signature has also changed.

### Other information:
PyWGBT was used as a comparison.

### CODE REVIEW

**Comment by aulemahal** [comment]
Before:
image

After:
image

The whole left half of the "before" was wrong because of mishandled radians. And the arctic circle was put to 0 because the "sunset" time was NaN.

**Review by Zeitsperre — APPROVED** [review]
Wow! Well done!

**Comment by Zeitsperre** [comment]
Merge when ready!

**Comment by ludwiglierhammer** [comment]
This is really great work. Thank you for fixing those glitches.

**Pull request merged**
