### PR TITLE
Added doy adjustments to indices using percentiles

### LINKED ISSUE #101: interpolate output of percentile_doy for indices using it.

### PR DESCRIPTION
**Pull request by huard**
* **Please check if the PR fulfills these requirements**
- [x] This PR addresses an already opened issue (for bug fixes / features)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, etc.)
* Use `adjust_doy_calendar` in indices using percentile values. 
* Created `infer_doy_max` and `interpolate_doy_calendar` to split the logic in `adjust_doy_calendar`. 

* **Does this PR introduce a breaking change?** (Has there been an API change?)
No. 

Fixes #101

### CODE REVIEW

**Comment by huard** [comment]
@Zeitsperre It seems the build does not pick the xarray version with the CFTimeIndex resampling. Ideas ?

**Comment by Zeitsperre** [comment]
@huard I found out the hard way this morning that the latest stable release of xarray does not integrate the work done by @jwenfai allowing for resampling with CF-Time calendars yet. An easy fix is to re-add the git URL for pydata/xarray@master to the `setup.py` requirements if you want passing tests for the time being.

**Comment by Zeitsperre** [comment]
I'm hoping that his work will be in the next stable release.

**Comment by huard** [comment]
Haven't be able to do that in the setup.py using 
`'xarray>0.11.3',`
 and 
`dependency_links=['http://github.com/pydata/xarray/tarball/master#egg=xarray-0.11.4'],`

Skipping test for now.

**Comment by Zeitsperre** [comment]
The dependency link approach is deprecated as of 2016. The approach I just tried that seems to work well is adding the following to requirements in `setupy.py`:

`'xarray @ https://api.github.com/repos/pydata/xarray/tarball/master'`

Unfortunately, the current master is incompatible with Python2.7. Quite the headache.

**Comment by sbiner** [comment]
Je trouve qu'avoir `interpolate_doy_calendar` et `adjust_doy_calendar` c'est un peu mélangeant et je suggère de les unir sous le nom `adjust_doy_calendar`.  Présentement `adjust_doy_calendar`ne fait pas grand chose. Ceci dit, ce n'est qu'une suggestion.

**Comment by huard** [comment]
Je trouvais que splitter en deux facilitait les tests. Ceci dit on pourrait renommer `interpolate..` vers `_interpolate..` pour éviter de contaminer le name space avec des fonctions qui se ressemblent trop.

**Comment by sbiner** [comment]
Ça me va. Pour le reste, ça me semble ok.

**Pull request merged**
