### PR TITLE
Coverage+Coveralls CI

### PR DESCRIPTION
**Pull request by Zeitsperre**
Attempting to set this up. Ideally, unit-testing will be done within a Tox environment and, assuming that tests pass, coverage testing will be reported to coveralls.io and report metrics here.

If anyone wants to help out (like @Balinus :+1:), feel free to add to the branch.

### CODE REVIEW

**Comment by Balinus** [comment]
The python 3.4 build errors is still the same as last week? 

Nice work! It's really useful to have the coverage tested.

**Comment by Zeitsperre** [comment]
Yeah, I'm not sure where the issue is. I'll try seeing if there's an issue with the availability of Python 3.4. The vms are built on Ubuntu so it's possible that 3.4 isn't readily available (ie: must be installed) prior to testing.

**Comment by Zeitsperre** [comment]
Also, please don't merge this; still several testing issues to fix.

**Comment by Balinus** [comment]
Python 3.4 is indeed downloaded and installed. The stalling occurs after, when requirements are installed. Tried locally and the package that takes the most time is Spinx and guzzle-sphinx-theme. Perhaps trying without them? Are they needed actually? I mean, I thought it was documentation-related.

**Comment by Balinus** [comment]
Just restarted manually the build and it worked. I often has this problem with ClimateTools.jl when building on OSX.

**Comment by Zeitsperre** [comment]
That's a good point. I'll try setting tox to only build docs on Python3.6. ReadTheDocs has its own webhooks so it doesn't really matter too much whether it builds or fails in Travis/Tox. I can even look into whether RtD can publish build checks here. If we want, I can start by compartmentalizing the docs-build.

**Pull request merged**
