### PR TITLE
Pin cftime

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)
- [ ] HISTORY.rst has been updated (with summary of main changes)
- [ ] `bumpversion (major / minor / patch)` has been called on this branch
- [ ] Tags have been pushed (`git push --tags`)

* **What kind of change does this PR introduce?** 
Pins cftime >= 1.2 < 1.4. Because 1.4 breaks xarray (pydata/xarray#4853).

* **Does this PR introduce a breaking change?** 
No.

* **Other information**:
I had not seen some of the bugs that appeared when testing #640. My first impression of a light bug was wrong and it seems all file-reading with cftime is broken.

### CODE REVIEW

**Review by tlogan2000 — APPROVED** [review]

**Review by Zeitsperre — APPROVED** [review]
If it breaks xarray, we can probably stand to wait a bit before upgrading. Thanks!

**Comment by tlvu** [comment]
@aulemahal Est-ce que par hasard ca fixerait cette erreur?

```
/opt/conda/envs/birdy/lib/python3.7/site-packages/xclim/core/calendar.py in <module>
     27
     28 # cftime and datetime classes to use for each calendar name
---> 29 datetime_classes = {"default": pydt.datetime, **cftime._cftime.DATE_TYPES}
     30
     31 # Maximum day of year in each calendar.AttributeError: module 'cftime._cftime' has no attribute 'DATE_TYPES'
```

**Comment by huard** [comment]
Je pense que oui.

**Comment by aulemahal** [comment]
@tlvu  Exact!

**Pull request merged**
