### PR TITLE
Patch release: V0.52.1

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGELOG.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Fixes a dependency pin that was causing environment resolution errors on PAVICS

### Does this PR introduce a breaking change?

No.

### Other information:

Private: https://github.com/Ouranosinc/pavics-jupyter-env-issues/issues/13#issuecomment-2343804116

### CODE REVIEW

**Review by tlvu — APPROVED** [review]
LGTM

**Comment by Zeitsperre** [comment]
This PR will bump the version to the next point patch version (`v0.52.2-dev.x`). I'll be proposing a better system soon to not run into this problem again.

**Comment by aulemahal** [comment]
I've been made aware that the latest release of xarray contains my changes concerning the "decimal_year" stuff which has broken xclim. I'll try to insert a fix here today!

**Comment by Zeitsperre** [comment]
@aulemahal v0.52.1 has already been released, unfortunately. I might need to push another patch, haha.

**Comment by aulemahal** [comment]
> has already been released

And I even approved the deployment :upside_down_face: . I was mislead by the fact that this PR was still open ;)!

**Pull request merged**
