### PR TITLE
CI cleanup

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [x] Tests for the changes have been added (for bug fixes / features)
  - [x] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Uses latest Ubuntu image (now 22.04)
* Install SBCK from official source master branch
* Ensure that tox used is always v3.0
* Fix a badly-referenced article (Not to proper article; URL was causing docs failures)

### Does this PR introduce a breaking change?

No.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@aulemahal 

Bad news: the SBCK that was being installed via CI was the version pegged at our contribution branch. I've now pointed this at the upstream dev branch of [yrobink/SBCK-python](https://github.com/yrobink/SBCK-python) and there are now some clear incompatibilities (that may have been introduced in the past few months). Issues are with the following tests:
```
FAILED xclim/testing/tests/test_sdba/test_adjustment.py::TestSBCKutils::test_sbck[True-SBCK_XClimNPPP] - AttributeError: 'XClimNPPP' object has no attribute '_bc_method'
FAILED xclim/testing/tests/test_sdba/test_adjustment.py::TestSBCKutils::test_sbck[True-SBCK_XClimSPPP] - AttributeError: 'XClimSPPP' object has no attribute '_bc_method'
```

Should we open an issue about this? Can it be solved easily here?

**Comment by aulemahal** [comment]
@juliettelavoie Are these the same errors as the ones you were receiving in your SBCK tests? (In the test-py310-opt-slow build).

**Comment by juliettelavoie** [comment]
No, I don't think I have seen this error before. During my tests, I was able to run dOTC on this small test dataset, the issues came up when doing it over a real big dataset.

**Comment by Zeitsperre** [comment]
@aulemahal should I pin to a specific commit for the time being?

**Comment by aulemahal** [comment]
Ok, let's revert to our branch and open an issue.

**Review by aulemahal — APPROVED** [review]

**Pull request merged**
