### PR TITLE
added jitter_over_thresh

### PR DESCRIPTION
**Pull request by RondeauG**
* **What kind of change does this PR introduce?** 
processing.py (in sdba) had a jitter_under_thresh function. This adds its counterpart, for variables such as relative humidity where there is a ceiling.

Because there is no equivalent to epsilon, there is a new parameter for the upper boundary.

* **Does this PR introduce a breaking change?** 

* **Other information**:

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@RondeauG 
```
conda install pre-commit
pre-commit install
pre-commit run --all-files
git add *
git commit -m "blackened`
git push
```

**Comment by RondeauG** [comment]
I added a new test for the function.

I also tried to use pre-commit, but I get an error at `pre-commit run --all-files`
```
An unexpected error has occurred: CalledProcessError: command: ('/(path_to_my_env)/pyscen/bin/python', '-mvirtualenv', '/(path_to_my_home)/.cache/pre-commit/repobn2xdaue/py_env-python3.6', '-p', 'python3.6')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
```

**Review by aulemahal — APPROVED** [review]

**Comment by aulemahal** [comment]
I ran the pre-commit hooks on my side. 
Thanks @RondeauG!

**Comment by Zeitsperre** [comment]
@RondeauG Sorry! That's the first time I see that error. I'll look into that. In the meantime, feel free to `conda remove pre-commit` if it continues to give you problems.

**Comment by RondeauG** [comment]
@Zeitsperre No problem! I run a semi-custom environment that would benefit from being cleaned up soon, so the issue is probably on my side.

**Pull request merged**
