### PR TITLE
Option to output datasets

### LINKED ISSUE #1257: Return Datasets
### Generic Issue

It could be interesting to (optionally) return Datasets when computing indicators. This could be controlled by `set_options`. 

It would allow:
- Adding  `time_bounds`
- Having correct CF attributes : "Conventions" and "history" are supposed to be at the dataset-level.
- Preserve `grid_mapping` and other metadata/auxiliary vars when a `ds` is passed to the indicator.
- Multiple output indicators in a single dataset

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #1257
- [x] Tests for the changes have been added (for bug fixes / features)
  - [x] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGES.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* New option : `as_dataset`. When True, indicators return Datasets instead of DataArrays or tuples thereof.

### Does this PR introduce a breaking change?
No.

### CODE REVIEW

**Review by Zeitsperre — COMMENTED** [review]
Cool!

Is there a particular reason why we wouldn't want to offer this as a method/call signature of Indicator objects? e.g. `some_indicator(..., as_dataset=True)`?

**Comment by aulemahal** [comment]
It's simply that I didn't want to add another argument to the indicators, as to now overcrowd the signature with parameters that do not impact the computation itself.

But, it could be done easily.

**Comment by Zeitsperre** [comment]
That's a good point. The workflow example is clear enough, so I don't see any harm from keeping this as an option set via context.

The only other way I could see this being implemented (for conventional `xarray` users, anyway) would involve extending `xarray.DataArray.to_dataset()`, but that could be either very easy or an absolute nightmare. Is extending a `DataArray` class method an acceptable/desirable thing to do?

**Comment by tlogan2000** [comment]
LGTM ... I think the context / set_options mode is a decent compromise

**Review by tlogan2000 — APPROVED** [review]

**Comment by Zeitsperre** [comment]
New black came out. I'll see what can be done.

**Comment by aulemahal** [comment]
Oh! I thought this was a python 3.8 issue...

**Comment by Zeitsperre** [comment]
FYI: https://github.com/psf/black/releases/tag/24.1.0

Looks like a bunch of breaking changes. I think I'm going to pin `black` to the pre-commit latest version so we don't run into this again. Will happen in a new PR.

**Pull request merged**
