### PR TITLE
Fix 1232

### LINKED ISSUE #1232: Losing attributes of coords when using weights in ensemble stats
### Setup Information

- Xclim version: '0.38.1-beta'
- Python version: 3.9
- Operating System: mac

### Description

When I add the `weights` argument to ensemble statistics, I lose the attributes of my coordinates.

I think this is related to the fact that the `weights` dataset only has a `realization` coord. 

### Steps To Reproduce

with weights:

```
datasets = pcat.search(processing_level= 'delta-+1.5C').to_dataset_dict(
                        xarray_open_kwargs={'decode_timedelta':False})

weights = xs.ensembles.generate_weights(datasets=datasets)
ens = xc.ensembles.create_ensemble(datasets)
stats= xc.ensembles.ensemble_mean_std_max_min(ens, weights=weights)
print(stats.horizon.attrs)
>>> {}
```
without weights:
```
datasets = pcat.search(processing_level= 'delta-+1.5C').to_dataset_dict(
                        xarray_open_kwargs={'decode_timedelta':False})
ens = xc.ensembles.create_ensemble(datasets)
stats= xc.ensembles.ensemble_mean_std_max_min(ens)
print(stats.horizon.attrs)
>>> {'baseline': '1850-1900'}
```

### Additional context

This is also an issue for ensemble_percentiles.

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by juliettelavoie**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #1232 
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] HISTORY.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* fixes 1232. Keeps coordinates attributes when using `weights` in ` ensemble_mean_std_max_min` and ` ensemble_percentiles`.

### Does this PR introduce a breaking change?
no

### CODE REVIEW

**Review by aulemahal — APPROVED** [review]
Looks good!

**Comment by aulemahal** [comment]
@Zeitsperre I'm not sure what is happenning here? Why is `coverage/coveralls` hanging, while no other builds are running? Do we need to push a new commit to trigger them?

**Comment by Zeitsperre** [comment]
@aulemahal That's odd. I thought I dealt with this earlier in another PR. The manual way would be to push another commit, but the labelling itself should have triggered another build. I can look further into this.

**Comment by juliettelavoie** [comment]
@Zeitsperre Do you want me to keep it open so you can investigate or push a commit now to merge it ?

**Comment by Zeitsperre** [comment]
Build failures should be fixed with #1237

**Pull request merged**
