### PR TITLE
Prepare v0.42.0

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [ ] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #xyz
- [x] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGES.rst has been updated (with summary of main changes)
  - [x] Link to issue (:issue:`number`) and pull request (:pull:`number`) has been added

### What kind of change does this PR introduce?

* Prepares version 0.42.0 of xclim

### Does this PR introduce a breaking change?

No.

### CODE REVIEW

**Review by aulemahal — APPROVED** [review]

**Comment by Zeitsperre** [comment]
The conda build seems to be returning `dims` in the wrong order **sometimes**. Let's play it safe and wait for Monday.

**Comment by Zeitsperre** [comment]
@aulemahal

Outside the NetCDF4-related crashes, there's one failing test due to recent changes; I'm wondering if the order here is important (i.e. requires changes to `make_criteria`):
```
 FAILED xclim/testing/tests/test_ensembles.py::TestEnsembleReduction::test_make_criteria - AssertionError: assert ('realization', 'time', 'lat') == ('realization', 'lat', 'time')
  At index 1 diff: 'time' != 'lat'
  Full diff:
  - ('realization', 'lat', 'time')
  ?                 -------
  + ('realization', 'time', 'lat')
  ?                       +++++++
```
If not, I'll adjust the test myself.

**Comment by aulemahal** [comment]
Hum, well, on one hand it wasn't my intention to _guarantee_ the dimension order, so we could indeed change this test to be a set comparison, ignoring the order. On the other hand, I don't see why the order would change ? Maybe different xarray versions would have different behaviour ? That would explain why it happens in the upstream build. I

I can push something.

**Comment by Zeitsperre** [comment]
There's a new Pandas (v2.0!) that is breaking a bunch of tests. https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#backwards-incompatible-api-changes

@Ouranosinc/xclim-core Should we pin pandas below v2.0 for this release?

**Comment by Zeitsperre** [comment]
@aulemahal more issues with `make_criteria`:
```
 ___________________ TestEnsembleReduction.test_make_criteria ___________________
[gw0] linux -- Python 3.10.10 /home/runner/micromamba-root/envs/xclim/bin/python3.10

self = <xclim.testing.tests.test_ensembles.TestEnsembleReduction object at 0x7f3c68f78d00>
tas_series = <function tas_series.<locals>._tas_series at 0x7f3c603f4550>

    def test_make_criteria(self, tas_series):
        ds = xr.Dataset(
            data_vars={
                "var_a": tas_series([0, 1, 2, 3]),
                "var_b": tas_series([0, 1, 2, 3]).expand_dims(lat=[45, 47]),
                "var_c": tas_series([0, 1, 2, 3]),
            }
        ).expand_dims(realization=["A", "B", "C"])
    
        crit = ensembles.make_criteria(ds)
        assert crit.dims == ("realization", "criteria")
        assert crit.criteria.size == 16
        uncrit = crit.unstack("criteria").to_dataset("variables")
        assert set(uncrit.data_vars.keys()) == {"var_a", "var_b", "var_c"}
        assert set(uncrit.var_a.dims) == {"realization", "lat", "time"}
    
        crit = ensembles.make_criteria(ds.var_b)
        assert crit.dims == ("realization", "criteria")
        assert crit.criteria.size == 8
        uncrit = crit.unstack("criteria")
>       assert ds.var_b.equals(uncrit)
E       AssertionError: assert False
E        +  where False = <bound method DataArray.equals of <xarray.DataArray 'var_b' (realization: 3, lat: 2, time: 4)>\narray([[[0, 1, 2, 3],\n        [0, 1, 2, 3]],\n\n       [[0, 1, 2, 3],\n        [0, 1, 2, 3]],\n\n       [[0, 1, 2, 3],\n        [0, 1, 2, 3]]])\nCoordinates:\n  * realization  (realization) object 'A' 'B' 'C'\n  * time         (time) datetime64[ns] 2000-07-01 2000-07-02 ... 2000-07-04\n  * lat          (lat) int64 45 47\nAttributes:\n    standard_name:  air_temperature\n    cell_methods:   time: mean within days\n    units:          K>(<xarray.DataArray 'criteria' (realization: 3, time: 4, lat: 2)>\narray([[[0, 0],\n        [1, 1],\n        [2, 2],\n        [3, 3]],\n\n       [[0, 0],\n        [1, 1],\n        [2, 2],\n        [3, 3]],\n\n       [[0, 0],\n        [1, 1],\n        [2, 2],\n        [3, 3]]])\nCoordinates:\n  * time         (time) datetime64[ns] 2000-07-01 2000-07-02 ... 2000-07-04\n  * lat          (lat) int64 45 47\n  * realization  (realization) object 'A' 'B' 'C'\nAttributes:\n    standard_name:  air_temperature\n    cell_methods:   time: mean within days\n    units:          K)
E        +    where <bound method DataArray.equals of <xarray.DataArray 'var_b' (realization: 3, lat: 2, time: 4)>\narray([[[0, 1, 2, 3],\n        [0, 1, 2, 3]],\n\n       [[0, 1, 2, 3],\n        [0, 1, 2, 3]],\n\n       [[0, 1, 2, 3],\n        [0, 1, 2, 3]]])\nCoordinates:\n  * realization  (realization) object 'A' 'B' 'C'\n  * time         (time) datetime64[ns] 2000-07-01 2000-07-02 ... 2000-07-04\n  * lat          (lat) int64 45 47\nAttributes:\n    standard_name:  air_temperature\n    cell_methods:   time: mean within days\n    units:          K> = <xarray.DataArray 'var_b' (realization: 3, lat: 2, time: 4)>\narray([[[0, 1, 2, 3],\n        [0, 1, 2, 3]],\n\n       [[0, 1, 2, 3],\n        [0, 1, 2, 3]],\n\n       [[0, 1, 2, 3],\n        [0, 1, 2, 3]]])\nCoordinates:\n  * realization  (realization) object 'A' 'B' 'C'\n  * time         (time) datetime64[ns] 2000-07-01 2000-07-02 ... 2000-07-04\n  * lat          (lat) int64 45 47\nAttributes:\n    standard_name:  air_temperature\n    cell_methods:   time: mean within days\n    units:          K.equals
E        +      where <xarray.DataArray 'var_b' (realization: 3, lat: 2, time: 4)>\narray([[[0, 1, 2, 3],\n        [0, 1, 2, 3]],\n\n       [[0, 1, 2, 3],\n        [0, 1, 2, 3]],\n\n       [[0, 1, 2, 3],\n        [0, 1, 2, 3]]])\nCoordinates:\n  * realization  (realization) object 'A' 'B' 'C'\n  * time         (time) datetime64[ns] 2000-07-01 2000-07-02 ... 2000-07-04\n  * lat          (lat) int64 45 47\nAttributes:\n    standard_name:  air_temperature\n    cell_methods:   time: mean within days\n    units:          K = <xarray.Dataset>\nDimensions:      (realization: 3, time: 4, lat: 2)\nCoordinates:\n  * realization  (realization) object 'A' 'B' 'C'\n  * time         (time) datetime64[ns] 2000-07-01 2000-07-02 ... 2000-07-04\n  * lat          (lat) int64 45 47\nData variables:\n    var_a        (realization, time) int64 0 1 2 3 0 1 2 3 0 1 2 3\n    var_b        (realization, lat, time) int64 0 1 2 3 0 1 2 ... 1 2 3 0 1 2 3\n    var_c        (realization, time) int64 0 1 2 3 0 1 2 3 0 1 2 3.var_b

xclim/testing/tests/test_ensembles.py:531: AssertionError
```

**Comment by Zeitsperre** [comment]
If we wish to add a conditional version pin for pandas in our conda package, this can be configured at the recipe level. The question we need to ask is whether we should.

**Review by aulemahal — APPROVED** [review]
The conditional pin here was needed because we still allow python 3.8 even though xarray doesn't. Sadly, the same would happen with conda environments...

**Pull request merged**
